title: Should I Tip In
description: >
  Your waiter brings you your cheque. $20, not bad. But crap—what country am I
  in? Do I tip here? How much? Oh God they're staring at me now. Help! Should
  I Tip In [Country]?

markdown: kramdown
collections:
  countries:
    output: true
    permalink: /:path/
gems:
  - jekyll-sitemap
